# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wl6eYo0_x7E0_ITgJlmg8ikYFBt4ntHg
"""




import streamlit as st
import pandas as pd
from joblib import load

# ================= PAGE CONFIG ================= #
st.set_page_config(
    page_title="Book Recommendation System",
    page_icon="📚",
    layout="wide"
)

# ================= SESSION ================= #
if "wishlist" not in st.session_state:
    st.session_state.wishlist = set()

# ================= UI STYLE (FLASK-LIKE LOOK) ================= #
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap');

html, body, [class*="css"] {
    font-family: 'Poppins', sans-serif;
    background-color: #f4f6fb;
    color: #1f2937;
    font-size: 18px;
}

.header {
    background: linear-gradient(90deg, #4f46e5, #9333ea);
    padding: 28px;
    border-radius: 18px;
    text-align: center;
    color: white;
    margin-bottom: 25px;
}
.header h1 { font-size: 40px; margin-bottom: 6px; }
.header p { font-size: 18px; }

button[data-baseweb="tab"] {
    font-size: 20px;
    padding: 14px 26px;
    font-weight: 600;
}

.section {
    background: white;
    padding: 32px;
    border-radius: 20px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.08);
    margin-bottom: 35px;
}

.book-card {
    background: white;
    border-radius: 18px;
    padding: 18px;
    text-align: center;
    box-shadow: 0 8px 22px rgba(0,0,0,0.08);
}

.book-title { font-size: 17px; font-weight: 600; }
.book-author { font-size: 15px; color: #6b7280; }

.stButton>button {
    background: linear-gradient(90deg, #4f46e5, #9333ea);
    color: white;
    border-radius: 12px;
    height: 48px;
    font-size: 17px;
    font-weight: 600;
}

.footer {
    text-align: center;
    font-size: 15px;
    color: #6b7280;
    margin-top: 40px;
}
</style>
""", unsafe_allow_html=True)

# ================= LOAD DATA ================= #
@st.cache_data
def load_data():
    item_sim = load("item_model.pkl")
    user_sim = load("user_model.pkl")
    user_isbn = load("user_isbn_matrix.pkl")
    books = pd.read_csv("book_details.csv")
    popularity = pd.read_csv("popularity.csv")
    return item_sim, user_sim, user_isbn, books, popularity

item_sim, user_sim, user_isbn, books, popularity = load_data()
books.columns = books.columns.str.strip()
book_meta = books.set_index("ISBN").to_dict("index")

# ================= HEADER ================= #
st.markdown("""
<div class="header">
    <h1>📚 Book Recommendation</h1>
    <p>Find books you’ll love — just like an e-commerce store</p>
</div>
""", unsafe_allow_html=True)

# ================= HELPERS ================= #
def book_card(isbn, key_prefix):
    meta = book_meta.get(isbn)
    if not meta:
        return

    st.image(meta["Image-URL-L"], width=140)
    st.markdown(f"<div class='book-title'>{meta['Book-Title']}</div>", unsafe_allow_html=True)
    st.markdown(f"<div class='book-author'>{meta['Book-Author']}</div>", unsafe_allow_html=True)
    st.markdown("⭐⭐⭐⭐")

    c1, c2 = st.columns(2)
    with c1:
        if st.button("❤️ Save", key=f"{key_prefix}_{isbn}"):
            st.session_state.wishlist.add(isbn)
            st.success("Added")
    with c2:
        link = f"https://www.google.com/search?q={meta['Book-Title'].replace(' ', '+')}+book"
        st.markdown(f"[View]({link})")

# ================= NAVIGATION ================= #
tab_home, tab_popular, tab_user, tab_item, tab_wish = st.tabs(
    ["🏠 Home", "🔥 Popular", "👤 User Based", "📖 Item Based", "❤️ Wishlist"]
)

# ================= HOME ================= #
with tab_home:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.write("""
    Welcome to the **Book Recommendation System**.

    ✔ Discover popular books
    ✔ Get personalized user recommendations
    ✔ Find similar books instantly
    ✔ Save books to wishlist

    Built with **Machine Learning + clean UI**.
    """)
    st.markdown('</div>', unsafe_allow_html=True)

# ================= POPULAR ================= #
with tab_popular:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    cols = st.columns(4)
    for i, isbn in enumerate(popularity.head(12)["ISBN"]):
        with cols[i % 4]:
            st.markdown('<div class="book-card">', unsafe_allow_html=True)
            book_card(isbn, "pop")
            st.markdown('</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

# ================= USER BASED ================= #
with tab_user:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    user_id = st.selectbox("Select User ID", sorted(user_sim.index.tolist()))
    if st.button("Recommend Books"):
        similar_users = user_sim.loc[user_id].sort_values(ascending=False)[1:6].index
        recs = user_isbn.loc[similar_users].mean().sort_values(ascending=False).head(6).index
        cols = st.columns(3)
        for i, isbn in enumerate(recs):
            with cols[i % 3]:
                st.markdown('<div class="book-card">', unsafe_allow_html=True)
                book_card(isbn, "user")
                st.markdown('</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

# ================= ITEM BASED ================= #
with tab_item:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    valid = set(books["ISBN"].astype(str)).intersection(set(item_sim.index.astype(str)))
    item_books = books[books["ISBN"].astype(str).isin(valid)]
    title = st.selectbox("Search Book", item_books["Book-Title"].tolist())
    isbn = str(item_books[item_books["Book-Title"] == title].iloc[0]["ISBN"])
    if st.button("Find Similar"):
        st.subheader("Selected Book")
        book_card(isbn, "item_sel")
        st.subheader("Similar Books")
        sims = item_sim.loc[isbn].sort_values(ascending=False)[1:7].index
        cols = st.columns(3)
        j = 0
        for s in sims:
            if str(s) in valid:
                with cols[j % 3]:
                    st.markdown('<div class="book-card">', unsafe_allow_html=True)
                    book_card(s, "item")
                    st.markdown('</div>', unsafe_allow_html=True)
                j += 1
    st.markdown('</div>', unsafe_allow_html=True)

# ================= WISHLIST ================= #
with tab_wish:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    if not st.session_state.wishlist:
        st.info("Wishlist is empty")
    else:
        cols = st.columns(3)
        for i, isbn in enumerate(st.session_state.wishlist):
            with cols[i % 3]:
                st.markdown('<div class="book-card">', unsafe_allow_html=True)
                book_card(isbn, "wish")
                st.markdown('</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

# ================= FOOTER ================= #
st.markdown("""
<div class="footer">
© 2025 Book Recommendation System
</div>
""", unsafe_allow_html=True)
